name: discovery_dns_sd
description: DNS-SD (Bonjour/NSD) implementation for peer discovery.
publish_to: 'none'
resolution: workspace

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  core_domain:
    path: ../../core/core_domain
  multicast_dns: ^0.3.2+2
  uuid: ^4.0.0

dev_dependencies:
  test: ^1.24.0