name: persistence_kv
description: Key-value storage implementation for settings and known peers.
publish_to: 'none'
resolution: workspace

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  core_domain:
    path: ../../core/core_domain
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15

dev_dependencies:
  test: ^1.24.0