name: core_usecases
description: Base use case types and helpers.
publish_to: 'none'
resolution: workspace

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  core_domain:
    path: ../core_domain
  equatable: ^2.0.5

dev_dependencies:
  test: ^1.24.0